# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
print(np.__version__)
print(np.show_config())


1.19.2
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/91870/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/91870/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/91870/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/91870/anaconda3\\Library\\include']
lapack_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/91870/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/91870/anaconda3\\Library\\include']
lapack_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/91870/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:/Users/91870/anaconda3\\Library\\include']
None


#### 3. Create a null vector of size 10

In [10]:
a=np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array

In [75]:
# consider an numpy array 
arr=np.array([2,3])
a=arr.size
b=arr.itemsize
print("{} bytes".format(a*b))

4
8 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [45]:
np.add?

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [49]:
a=np.zeros(10)
a[5]=1
print(a)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49

In [50]:
a=np.arange(10,50)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last)

In [51]:
np.flipud(a)


array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [54]:
a=np.random.randint(0,9,(3,3))
print(a)

[[8 8 7]
 [2 0 0]
 [1 1 5]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [57]:
a=np.array([1,2,0,0,4,0])
ans=np.nonzero(a)
print(ans)

(array([0, 1, 4], dtype=int64),)


#### 11. Create a 3x3 identity matrix

In [40]:
arr=np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [62]:
arr=np.random.random((3,3,3))
print(arr)

[[[0.61523451 0.53083832 0.47109801]
  [0.92680478 0.77490515 0.6695224 ]
  [0.8092219  0.59473068 0.18014618]]

 [[0.09202263 0.78154399 0.40092712]
  [0.27529673 0.21701134 0.73249115]
  [0.27846609 0.25245116 0.00127599]]

 [[0.34384248 0.61277032 0.55069627]
  [0.72578742 0.47864864 0.38305778]
  [0.661332   0.31821619 0.51577777]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [73]:
arr=np.random.random((10,10))
print(arr)
print(arr.min())
print(arr.max())

[[0.75387974 0.35489628 0.76031083 0.46176402 0.80842473 0.36932451
  0.35186609 0.44354148 0.14732886 0.05896689]
 [0.90558016 0.62190271 0.45058695 0.30977056 0.80893659 0.81624211
  0.12864432 0.01085485 0.13211932 0.62100863]
 [0.35162622 0.60982136 0.6544176  0.79249849 0.29633361 0.91750539
  0.62208653 0.78004405 0.29328629 0.38592038]
 [0.50511294 0.03839698 0.72469299 0.73179416 0.20600571 0.5121202
  0.9421405  0.25483218 0.72228207 0.00676591]
 [0.95295125 0.86468069 0.52841664 0.59743539 0.06297443 0.90583012
  0.84047886 0.75968142 0.50286054 0.65558277]
 [0.49180053 0.54307819 0.48376195 0.6122203  0.85927817 0.28332005
  0.97899943 0.88545512 0.16667426 0.94348618]
 [0.40110322 0.18133406 0.89730501 0.13056802 0.45655057 0.67350385
  0.6869052  0.56742961 0.27677341 0.13186635]
 [0.30128242 0.13315877 0.57351805 0.60390715 0.59077237 0.34842636
  0.56301722 0.38259049 0.11477897 0.37514728]
 [0.77322892 0.26689876 0.54159378 0.90896711 0.72882215 0.96448165
  0.52710978 

#### 14. Create a random vector of size 30 and find the mean value

In [80]:
a=np.random.random((30))
np.mean(a)
a.mean()

0.47189843953337063

#### 15. Create a 2d array with 1 on the border and 0 inside

In [96]:
arr=np.ones((5,5))
arr[1:4,1:4]=0
print(arr)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [99]:
a=np.ones((5,5))
np.pad(a,pad_width=1,constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [101]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3*0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [118]:
a=np.ones((5,5))
a = np.diag([1,2,3],1)
a

array([[0, 1, 0, 0],
       [0, 0, 2, 0],
       [0, 0, 0, 3],
       [0, 0, 0, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [127]:
ans = np.zeros((8,8),dtype=int)
ans[1::2,::2] = 1
ans[::2,1::2] = 1
ans

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [122]:
np.unravel_index(99, (6,7,8))

(1, 5, 3)